### PR TITLE
issue:#18 type cast error

### PR DESCRIPTION
**Pull request by Abdulazeezvp**

### CODE REVIEW

**Review by kechankrisna — COMMENTED** [review]
Why need to await and check type first, while we can declare isConnected as dynamic and check type of result, so we will benefit from calling await 2 times

**Comment by necessarylion** [comment]
Can you help me to merge this PR?
I cannot print due to type issue.
Flutter 2.10.5 • channel stable.

**Comment by elliotrtd** [comment]
@kechankrisna Why did you close this without merging the changes?
This is still completely broken for me (and I assume others) without the change. 
I updated my local branch but that doesn't help for builds across multiple machines

**Comment by kechankrisna** [comment]
> @kechankrisna Why did you close this without merging the changes?
> This is still completely broken for me (and I assume others) without the change. 
> I updated my local branch but that doesn't help for builds across multiple machines

Sorry I will recheck it again

**Comment by elliotrtd** [comment]
Thanks!

The edit above fixes the problem, I did it the same way in my local branch as the original PR. 

I do want to say - your package is great, it is by FAR the easiest to work with of all the bluetooth POS printer packages and I think I tried nearly all & so far it's working near flawlessly so great job!

**Pull request closed without merging**
